# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 13

      
    - name: Setup environment
      run: yarn install

    # Runs a single command using the runners shell
    - name: Run tests
      run: yarn test

    # Runs a set of commands using the runners shell
    - name: Build project
      run: yarn run build

    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(git log -1 --pretty=%h)
    
    - name: Build and publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gunnarholwerda/turnip-tracker/discord-bot
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        tags: "latest,${{ env.RELEASE_VERSION }}"
